kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi-gluster-admin 
subjects:
  - kind: ServiceAccount
    name: heketi-service-account
    namespace: storage
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
