---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: redis
  labels:
    app: gitlab
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: gitlab
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gitlab
  name: redis
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: backend
    spec:
      containers:
        - image: redis:3.0.7-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis
              mountPath: /data
              subPath: redis
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: glusterfs-pvc 
        - name: host-time
          hostPath:
            path: /etc/localtime
