apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://120.27.22.209:8089/ci"
      token = "-9zuoJx3cyiVtE5yKSst"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        cert_file = "/etc/ssl/kubernetes/kubernetes.pem"
        key_file = "/etc/ssl/kubernetes/kubernetes-key.pem"
        ca_file = "/etc/ssl/kubernetes/ca.pem"
