---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: postgresql
  labels:
    app: gitlab
spec:
  ports:
    - port: 5432
  selector:
    app: gitlab
    tier: postgreSQL
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gitlab
  name: postgresql
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_DB
              value: gitlabhq_production
            - name: POSTGRES_PASSWORD
              value: gitlab
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: glusterfs-pvc 
        - name: host-time
          hostPath:
            path: /etc/localtime
