cluster.name: kubernetes-logging

node.name: ${NODE_NAME}
node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}

transport.tcp.port: ${TRANSPORT_PORT}
http.port: ${HTTP_PORT}

path.data: /data

network.host: 0.0.0.0

discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}

xpack.security.enabled: false
xpack.monitoring.enabled: false

index.cache.field.max_size: 50000 
index.cache.field.expire: 10m 
index.cache.field.type: soft 
